---
- name: install Netplan
  ansible.builtin.apt:
    name:
      - netplan.io
    state: present
    force_apt_get: yes
    update_cache: yes

- name: set Netplan configuration
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/netplan/config.yaml
    lstrip_blocks: yes
    mode: u=rw,g=r,o=r
  notify:
    - netplan apply
