---
- name: converge
  hosts: host1:host2
  tasks:
    - name: install test dependencies
      ansible.builtin.apt:
        name:
          - iputils-ping
          - ifupdown
          # Fixes Netplan failure. The following exception is thrown on
          # "netplan apply" command execution:
          # FileNotFoundError: [Errno 2] No such file or directory: 'udevadm'
          - udev
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: configure Netplan
      ansible.builtin.import_role:
        name: netplan
