---
- name: prepare
  hosts: host1:host2
  gather_facts: no
  tasks:
    - name: install Ansible dependencies
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get update && apt-get install --yes python3-minimal)
      changed_when: no
